
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvbovmxdzcgizjktafxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52Ym92bXhkemNnaXpqa3RhZnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDY0MzYsImV4cCI6MjA1OTE4MjQzNn0.pk4xH_At2aOFPLbKcEe369fuwoSJa0IQ0ebCZdvrby0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storageKey: 'taskbridge-auth',
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
